security:
  providers:
    ctp:
      id: commercetools.user_provider
  access_control:
  - { path: /user/, roles: ROLE_USER }
  encoders:
    Symfony\Component\Security\Core\User\User: plaintext
    Commercetools\Symfony\CtpBundle\Security\User\User: plaintext
  firewalls:
    main:
      anonymous: ~
      commercetools-login:
        login_path: login
        check_path: login_check
        default_target_path: _ctp_example_index
      logout:
        path:   logout
        target: _ctp_example_index
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    default:
      anonymous: ~