setup:
    custom_types:
        payment2order:
            id: 8d383d2a-cc86-4a18-ad5c-31d6281a6ca5
            key: payment2order
            name:
                en: order2payment
            description:
                en: payment2order2
            resourceTypeIds:
                - payment
            fieldDefinitions:
                OrderReference:
                    name: OrderReference
                    label:
                        en: order-id-custom
                    required: true
                    type:
                        name: String
                    inputHint: SingleLine
        asfgad:
            id: bba3324a-f7c8-45dd-81ad-b4865d2db924
            key: asfgad
            name:
                en: asdga2
            description:
                en: asdga
            resourceTypeIds:
                - payment
            fieldDefinitions:
                OrderReference:
                    name: OrderReference
                    label:
                        en: order-id
                    required: true
                    type:
                        name: String
                    inputHint: SingleLine
        vita:
            id: 8e3e08d2-0d86-42ef-866e-2e0d372156b1
            key: vita
            name:
                en: vita
            description:
                en: vita
            resourceTypeIds:
                - line-item
                - channel
                - discount-code
                - product-price
            fieldDefinitions: {  }
        anotherType:
            id: 169ff392-3b8f-4a15-97b7-31bc648d8716
            key: anotherType
            name:
                en: anotherType
            description:
                en: anotherType
            resourceTypeIds:
                - shopping-list
            fieldDefinitions:
                whomsdt:
                    name: whomsdt
                    label:
                        en: whomsdt
                    required: true
                    type:
                        name: String
                    inputHint: SingleLine
        asdf:
            id: 2484f03f-8c6e-4af1-a06d-f3a14f6857d5
            key: asdf
            name:
                en: asdf
            description:
                en: asdf
            resourceTypeIds:
                - line-item
            fieldDefinitions: {  }
        alfa:
            id: 20014beb-649d-4c5a-8da0-c92d26f0ed36
            key: alfa
            name:
                en: alfa
            description:
                en: alfa
            resourceTypeIds:
                - line-item
            fieldDefinitions:
                vita:
                    name: vita
                    label:
                        en: vita
                    required: true
                    type:
                        name: String
                    inputHint: SingleLine
        gama:
            id: 12307736-9010-4c81-b136-b5d1f4274958
            key: gama
            name:
                en: gama
            description:
                en: gama
            resourceTypeIds:
                - shopping-list
            fieldDefinitions:
                eo:
                    name: eo
                    label:
                        en: eo
                    required: true
                    type:
                        name: String
                    inputHint: SingleLine
        booleanCustomType:
            id: b2d6aa7a-b4b6-4f29-8ad9-38ea464fa3ad
            key: booleanCustomType
            name:
                en: booleanCustomType
            description:
                en: booleanCustomType
            resourceTypeIds:
                - review
            fieldDefinitions:
                eoi:
                    name: eoi
                    label:
                        en: eoi
                    required: true
                    type:
                        name: Boolean
                    inputHint: SingleLine
        wow:
            id: 2dffd580-b81c-4e23-9b5f-604a493bdfe3
            key: wow
            name:
                en: wow
            description:
                en: wow
            resourceTypeIds:
                - discount-code
            fieldDefinitions:
                iu:
                    name: iu
                    label:
                        en: iu
                    required: true
                    type:
                        name: Time
                    inputHint: SingleLine
        asfl:
            id: 5798fb80-01be-4bb1-b3ca-848dd55bdd52
            key: asfl
            name:
                en: asfl
            description:
                en: asfl
            resourceTypeIds:
                - discount-code
            fieldDefinitions:
                ai:
                    name: ai
                    label:
                        en: ai
                    required: true
                    type:
                        name: Number
                    inputHint: SingleLine
        pew:
            id: c55bd7ab-00e7-4887-8bef-440807ff7afb
            key: pew
            name:
                en: pew
            description:
                en: pew
            resourceTypeIds:
                - discount-code
                - customer-group
                - channel
            fieldDefinitions:
                geld:
                    name: geld
                    label:
                        de: geld
                    required: true
                    type:
                        name: String
                    inputHint: SingleLine
        custom-type-custom-custom:
            id: 11660b13-f0bf-4473-ab6b-00061621ce53
            key: custom-type-custom-custom
            name:
                en: custom-type-name
            description:
                en: custom-type-name-desc
            resourceTypeIds:
                - line-item
                - shopping-list
                - channel
            fieldDefinitions:
                field-23:
                    name: field-23
                    label:
                        en: field-1-label22
                    required: true
                    type:
                        name: String
                    inputHint: SingleLine
        eor233:
            id: d5005148-51a5-4686-b22d-b5d983972d2f
            key: eor233
            name:
                en: eor
            description:
                en: eor
            resourceTypeIds:
                - review
            fieldDefinitions:
                oioi:
                    name: oioi
                    label:
                        en: oi333
                    required: true
                    type:
                        name: String
                    inputHint: SingleLine
        paymentsRelations:
            id: 17b633cc-b8a0-4ed5-9ade-bf937ff19168
            key: paymentsRelations
            name:
                en: RelatePayments
            description:
                en: RelatePayments
            resourceTypeIds:
                - payment
            fieldDefinitions:
                cartReference:
                    name: cartReference
                    label:
                        en: cartReference
                    required: false
                    type:
                        name: String
                    inputHint: SingleLine
                orderReference:
                    name: orderReference
                    label:
                        en: orderReference
                    required: false
                    type:
                        name: String
                    inputHint: SingleLine
        asf:
            id: c9ddb89b-c193-494b-b577-5e2492cc2b55
            key: asf
            name:
                en: dsf
            description:
                en: dsf
            resourceTypeIds:
                - channel
            fieldDefinitions:
                af:
                    name: af
                    label:
                        en: fa
                    required: false
                    type:
                        name: Number
                    inputHint: SingleLine
        custom-type-5:
            id: 4b8da54e-57cb-4eff-b949-e6e65cd7c389
            key: custom-type-5
            name:
                en: custom-label122
            description:
                en: custom-label1
            resourceTypeIds:
                - line-item
                - channel
                - product-price
            fieldDefinitions: {  }
        two3:
            id: 91d613d1-2eb9-4baf-ad33-020ea04eb988
            key: two3
            name:
                en: another
            description:
                en: two
            resourceTypeIds:
                - payment
                - review
            fieldDefinitions:
                alfa:
                    name: alfa
                    label:
                        en: alfa144
                    required: false
                    type:
                        name: String
                    inputHint: SingleLine
                field22:
                    name: field22
                    label:
                        en: field22
                    required: true
                    type:
                        name: String
                    inputHint: SingleLine
        ok:
            id: d5963add-af68-419b-8d79-0fcf8a2a55e5
            key: ok
            name:
                en: oi-iu-OI-P
            description:
                en: io
            resourceTypeIds:
                - shopping-list
            fieldDefinitions:
                ioj:
                    name: ioj
                    label:
                        en: oijk
                    required: true
                    type:
                        name: LocalizedString
                    inputHint: SingleLine
                foobarbar:
                    name: foobarbar
                    label:
                        en: fobar-lable
                    required: true
                    type:
                        name: LocalizedString
                    inputHint: SingleLine
        custom-type-key:
            id: 7c25cfed-e46f-493c-9d98-cf64c4b6aabd
            key: custom-type-key
            name:
                en: custom-type-name1wwe
            description:
                en: custom-type-name1
            resourceTypeIds:
                - discount-code
                - product-price
                - customer-group
            fieldDefinitions:
                how-many:
                    name: how-many
                    label:
                        en: how-many3423423
                    required: false
                    type:
                        name: Money
                    inputHint: SingleLine
        afaffasf:
            id: 7ed2c37a-709f-426a-ab83-cae89a7121a0
            key: afaffasf
            name:
                en: another-name
            description:
                en: asfsafag
            resourceTypeIds:
                - review
            fieldDefinitions:
                field:
                    name: field
                    label:
                        en: field-name
                    required: false
                    type:
                        name: Number
                    inputHint: SingleLine
        order2pay:
            id: f15be1f5-07e7-4748-8c61-23cb83f1e49d
            key: order2pay
            name:
                en: order2pay
            description:
                en: order2pay
            resourceTypeIds:
                - payment
            fieldDefinitions:
                orderReference:
                    name: orderReference
                    label:
                        en: order-id
                    required: true
                    type:
                        name: String
                    inputHint: SingleLine
                orderReference22:
                    name: orderReference22
                    label:
                        en: order-id
                    required: true
                    type:
                        name: String
                    inputHint: SingleLine
                orderReference334:
                    name: orderReference334
                    label:
                        en: order-id-dasd
                    required: true
                    type:
                        name: String
                    inputHint: SingleLine
