<?php

return [
    Symfony\Bundle\FrameworkBundle\FrameworkBundle::class => ['all' => true],
    Symfony\Bundle\TwigBundle\TwigBundle::class => ['all' => true],
    Symfony\Bundle\SwiftmailerBundle\SwiftmailerBundle::class => ['all' => true],
    Symfony\Bundle\SecurityBundle\SecurityBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineCacheBundle\DoctrineCacheBundle::class => ['all' => true],
    Doctrine\Bundle\DoctrineBundle\DoctrineBundle::class => ['all' => true],
    Doctrine\Bundle\MigrationsBundle\DoctrineMigrationsBundle::class => ['all' => true],
    Symfony\Bundle\MonologBundle\MonologBundle::class => ['all' => true],
    Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle::class => ['all' => true],
    Symfony\Bundle\WebProfilerBundle\WebProfilerBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\DebugBundle\DebugBundle::class => ['dev' => true, 'test' => true],
    Symfony\Bundle\MakerBundle\MakerBundle::class => ['dev' => true],
    Symfony\Bundle\WebServerBundle\WebServerBundle::class => ['dev' => true],
    Commercetools\Symfony\CtpBundle\CtpBundle::class => ['all' => true],
    Commercetools\Symfony\ShoppingListBundle\ShoppingListBundle::class => ['all' => true],
    Commercetools\Symfony\CartBundle\CartBundle::class => ['all' => true],
    Commercetools\Symfony\CustomerBundle\CustomerBundle::class => ['all' => true],
    Commercetools\Symfony\ReviewBundle\ReviewBundle::class => ['all' => true],
    Commercetools\Symfony\CatalogBundle\CatalogBundle::class => ['all' => true],
    Commercetools\Symfony\ExampleBundle\ExampleBundle::class => ['all' => true],
    Commercetools\Symfony\SetupBundle\SetupBundle::class => ['all' => true],
    Commercetools\Symfony\StateBundle\StateBundle::class => ['all' => true],
];
